### ISSUE TITLE
求教：关于支持分组攒批

### ISSUE THREAD

**Issue by dyrnq** [AHUCodingBeast/Waiting-Batch-Bus#1]
大佬，您好，首先感谢您开源的项目。

想请问下
1、分组攒批ProducerConfig其中的如下的配置是针对单个组的还是所有组总和的。
```bash
// 设定攒批达到20条以上的时候再执行业务逻辑
producerConfig.setBatchCountThreshold(20);
// 设定攒批已经达到100s的时候再执行业务逻辑
producerConfig.setLingerMs(100_000);
```
2、分组后，通过`messageProducer.send(null, messageList, (result) -> {})`第一个参数<https://github.com/AHUCodingBeast/Waiting-Batch-Bus/blob/master/src/main/java/com/waiting/bus/core/MessageProducer.java#L120>

那么消费的时候也可以按照send分组的拿回来分组消费吗？eg. 21个groupA ,然后达到了20的BatchCountThreshold，这里便的消息全是groupA的，而不包含groupB的？ 相当于一个多租户隔离的效果:)

**Comment by AHUCodingBeast** [comment]
不好意思现在才回复 
第一个问题是针对单个分组的，针对全部分组总和的，全局的则在ProducerConfig 有另一个参数totalSizeInBytes可以设置，为了避免让用户设置太多参数，这里这个参数有默认值。
第二个问题，暂时不支持，设置不同分组的目的是支持区分不同的消息处理方式，例如接收上游消息然后根据不同Tag分到不同的攒批分组中执行不同的处理逻辑。

**Comment by dyrnq** [comment]
感谢大佬回复
